v = input('digite qualquer coisa: ')
print(f'tipo primitivo: {type(v)}')
print('todas as letras são maiúsculas? ', v.isupper())
print('é uma string? ', v.isalpha()) 
print('é um número? ', v.isnumeric()) 
print('é um número decimal? ', v.isdecimal()) 
print('os caracteres são alfanuméricos? ', v.isalnum())
print('é um caractere US-ASCII de 7–bit válido? ', v.isascii())
print('é composta apenas por dígitos (0 a 9)? ', v.isdigit())
print('a string é um identificador válido? ', v.isidentifier())
print('todas as letras são minúsculas? ', v.islower())
print('os caracteres são imprimíveis? ', v.isprintable())
print('todos os caracteres estão em branco? ', v.isspace())
print('está capitalizado? ', v.istitle())